### ISSUE TITLE
Remove the unused samples and tests

### ISSUE THREAD

**Issue by munkhuushmgl** [googleapis/java-video-intelligence#301]
List of samples need to be deleted:
video_detect_text_beta
video_detect_text_gcs_beta
video_object_tracking_beta
video_object_tracking_gcs_beta
video_speech_transcription_gcs_beta
video_detect_logo_beta
video_detect_logo_gcs_beta

**Comment by suztomo** [comment]
Sample have been migrated https://github.com/googleapis/java-video-intelligence/pull/1084
